
export const dataSource = [
  {
    key: "1",
    user_id: 32,
    position: 1,
    name: "Muhaman Ijaz",
    email: "muhaman@example.com",
    masteries: [ "badges_roadmap_completion_6", "badges_contribution_6", "badges_time_on_platform_6", ],
    points: 768,
    roadmap_id: null,
    onboarded_id: 101,
  },
  {
    key: "2",
    user_id: 31,
    position: 2,
    name: "John Doe",
    email: "john.doe@example.com",
    masteries: ["badges_roadmap_completion_1", "badges_contribution_3"],
    points: 652,
    roadmap_id: 201,
    onboarded_id: null,
  },
  {
    key: "3",
    user_id: 23,
    position: 3,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    masteries: [ "badges_roadmap_completion_1", "badges_contribution_3", "badges_community_engagement_4", ],
    points: 600,
    roadmap_id: null,
    onboarded_id: null,
  },
  {
    key: "4",
    user_id: 25,
    position: 4,
    name: "Emily Clark",
    email: "emily.clark@example.com",
    masteries: [ "badges_achievement_3", "badges_contribution_3", "badges_time_on_platform_6", ],
    points: 580,
    roadmap_id: 204,
    onboarded_id: 102,
  },
  {
    key: "5",
    user_id: 2,
    position: 5,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    masteries: [ "badges_achievement_1", "badges_contribution_4", "badges_time_on_platform_2", ],
    points: 570,
    roadmap_id: null,
    onboarded_id: 103,
  },
  {
    key: "6",
    user_id: 6,
    position: 6,
    name: "Sophia Green",
    email: "sophia.green@example.com",
    masteries: ["badges_roadmap_completion_2", "badges_contribution_5"],
    points: 540,
    roadmap_id: null,
    onboarded_id: null,
  },
  {
    key: "7",
    user_id: 8,
    position: 7,
    name: "David White",
    email: "david.white@example.com",
    masteries: ["badges_achievement_3", "badges_time_on_platform_6"],
    points: 520,
    roadmap_id: 207,
    onboarded_id: null,
  },
  {
    key: "8",
    user_id: 9,
    position: 8,
    name: "Olivia Miller",
    email: "olivia.miller@example.com",
    masteries: [ "badges_achievement_3", "badges_contribution_3", "badges_time_on_platform_6", ],
    points: 510,
    roadmap_id: null,
    onboarded_id: 104,
  },
  {
    key: "9",
    user_id: 29,
    position: 9,
    name: "William Johnson",
    email: "william.johnson@example.com",
    masteries: [ "badges_achievement_2", "badges_contribution_1", "badges_time_on_platform_3", ],
    points: 500,
    roadmap_id: 209,
    onboarded_id: 105,
  },
  {
    key: "10",
    user_id: 19,
    position: 10,
    name: "Ava Davis",
    email: "ava.davis@example.com",
    masteries: [ "badges_achievement_1", "badges_contribution_1", "badges_time_on_platform_1", ],
    points: 490,
    roadmap_id: null,
    onboarded_id: null,
  },{
    key: "11",
    user_id: 132,
    position: 11,
    name: "Muhaman Ijaz",
    email: "muhaman@example.com",
    masteries: [ "badges_roadmap_completion_6", "badges_contribution_6", "badges_time_on_platform_6", ],
    points: 768,
    roadmap_id: null,
    onboarded_id: 101,
  },
  {
    key: "12",
    user_id: 131,
    position: 12,
    name: "John Doe",
    email: "john.doe@example.com",
    masteries: ["badges_roadmap_completion_1", "badges_contribution_3"],
    points: 652,
    roadmap_id: 201,
    onboarded_id: null,
  },
  {
    key: "13",
    user_id: 123,
    position: 13,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    masteries: [ "badges_roadmap_completion_1", "badges_contribution_3", "badges_community_engagement_4", ],
    points: 600,
    roadmap_id: null,
    onboarded_id: null,
  },
  {
    key: "14",
    user_id: 125,
    position: 14,
    name: "Emily Clark",
    email: "emily.clark@example.com",
    masteries: [ "badges_achievement_3", "badges_contribution_3", "badges_time_on_platform_6", ],
    points: 580,
    roadmap_id: 204,
    onboarded_id: 102,
  },
  {
    key: "15",
    user_id: 12,
    position: 15,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    masteries: [ "badges_achievement_1", "badges_contribution_4", "badges_time_on_platform_2", ],
    points: 570,
    roadmap_id: null,
    onboarded_id: 103,
  },
  {
    key: "16",
    user_id: 16,
    position: 16,
    name: "Sophia Green",
    email: "sophia.green@example.com",
    masteries: ["badges_roadmap_completion_2", "badges_contribution_5"],
    points: 540,
    roadmap_id: null,
    onboarded_id: null,
  },
  {
    key: "17",
    user_id: 18,
    position: 17,
    name: "David White",
    email: "david.white@example.com",
    masteries: ["badges_achievement_3", "badges_time_on_platform_6"],
    points: 520,
    roadmap_id: 207,
    onboarded_id: null,
  },
  {
    key: "18",
    user_id: 19,
    position: 18,
    name: "Olivia Miller",
    email: "olivia.miller@example.com",
    masteries: [ "badges_achievement_3", "badges_contribution_3", "badges_time_on_platform_6", ],
    points: 510,
    roadmap_id: null,
    onboarded_id: 104,
  },
  {
    key: "19",
    user_id: 129,
    position: 19,
    name: "William Johnson",
    email: "william.johnson@example.com",
    masteries: [ "badges_achievement_2", "badges_contribution_1", "badges_time_on_platform_3", ],
    points: 500,
    roadmap_id: 209,
    onboarded_id: 105,
  },
  {
    key: "20",
    user_id: 219,
    position: 20,
    name: "Ava Davis",
    email: "ava.davis@example.com",
    masteries: [ "badges_achievement_1", "badges_contribution_1", "badges_time_on_platform_1", ],
    points: 490,
    roadmap_id: null,
    onboarded_id: null,
  },{
    key: "21",
    user_id: 232,
    position: 21,
    name: "Muhaman Ijaz",
    email: "muhaman@example.com",
    masteries: [ "badges_roadmap_completion_6", "badges_contribution_6", "badges_time_on_platform_6", ],
    points: 768,
    roadmap_id: null,
    onboarded_id: 101,
  },
  {
    key: "22",
    user_id: 231,
    position: 22,
    name: "John Doe",
    email: "john.doe@example.com",
    masteries: ["badges_roadmap_completion_1", "badges_contribution_3"],
    points: 652,
    roadmap_id: 201,
    onboarded_id: null,
  },
  {
    key: "23",
    user_id: 223,
    position: 23,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    masteries: [ "badges_roadmap_completion_1", "badges_contribution_3", "badges_community_engagement_4", ],
    points: 600,
    roadmap_id: null,
    onboarded_id: null,
  },
  {
    key: "24",
    user_id: 225,
    position: 24,
    name: "Emily Clark",
    email: "emily.clark@example.com",
    masteries: [ "badges_achievement_3", "badges_contribution_3", "badges_time_on_platform_6", ],
    points: 580,
    roadmap_id: 204,
    onboarded_id: 102,
  },
  {
    key: "25",
    user_id: 22,
    position: 225,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    masteries: [ "badges_achievement_1", "badges_contribution_4", "badges_time_on_platform_2", ],
    points: 570,
    roadmap_id: null,
    onboarded_id: 103,
  },
  {
    key: "26",
    user_id: 26,
    position: 26,
    name: "Sophia Green",
    email: "sophia.green@example.com",
    masteries: ["badges_roadmap_completion_2", "badges_contribution_5"],
    points: 540,
    roadmap_id: null,
    onboarded_id: null,
  },
  {
    key: "27",
    user_id: 28,
    position: 27,
    name: "David White",
    email: "david.white@example.com",
    masteries: ["badges_achievement_3", "badges_time_on_platform_6"],
    points: 520,
    roadmap_id: 207,
    onboarded_id: null,
  },
  {
    key: "28",
    user_id: 29,
    position: 28,
    name: "Olivia Miller",
    email: "olivia.miller@example.com",
    masteries: [ "badges_achievement_3", "badges_contribution_3", "badges_time_on_platform_6", ],
    points: 510,
    roadmap_id: null,
    onboarded_id: 104,
  },
  {
    key: "29",
    user_id: 229,
    position: 29,
    name: "William Johnson",
    email: "william.johnson@example.com",
    masteries: [ "badges_achievement_2", "badges_contribution_1", "badges_time_on_platform_3", ],
    points: 500,
    roadmap_id: 209,
    onboarded_id: 105,
  },
  {
    key: "30",
    user_id: 219,
    position: 30,
    name: "Ava Davis",
    email: "ava.davis@example.com",
    masteries: [ "badges_achievement_1", "badges_contribution_1", "badges_time_on_platform_1", ],
    points: 490,
    roadmap_id: null,
    onboarded_id: null,
  },
];

export const singleUser = [
  {
    key: "8",
    user_id: 9,
    position: 8,
    name: "Olivia Miller",
    email: "olivia.miller@example.com",
    masteries: [ "badges_achievement_3", "badges_contribution_3", "badges_time_on_platform_6", ],
    points: 510,
    roadmap_id: null,
    onboarded_id: 104,
  },
];
