// src/redux/Types.js

export const SET_AUTH_TOKEN = 'SET_AUTH_TOKEN';
export const REMOVE_AUTH_TOKEN = 'REMOVE_AUTH_TOKEN';
export const SET_LOGGED_IN = 'SET_LOGGED_IN';
export const RERENDER_TRIBE_PAGE = 'RERENDER_TRIBE_PAGE'
export const RERENDER_APP = 'RERENDER_APP'
export const SET_BLIND_MODE = 'SET_BLIND_MODE'
export const SET_USER_ATTRIBUTES = 'SET_USER_ATTRIBUTES'
export const REFETCH_TRIBE_MEMBERS = 'REFETCH_TRIBE_MEMBERS'